apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-fycdhiwe
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-fycdhiwe:2890f90394f9aadde0398c78a4b1b7d004d202be@sha256:3736b9d397d4c269b352f070529bd839e5ccbad6048647bace54a68677fe1b01
        name: container-image  
